# Generated by Django 5.1.1 on 2025-01-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_categorymodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartmodel",
            name="meat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.meatmodel",
            ),
        ),
        migrations.AddField(
            model_name="cartmodel",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.sizemodel",
            ),
        ),
        migrations.AddField(
            model_name="cartmodel",
            name="spicy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.spicymodel",
            ),
        ),
    ]
