# Generated by Django 5.1.1 on 2025-01-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_cartmodel_meat_cartmodel_size_cartmodel_spicy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="quantity",
        ),
        migrations.AddField(
            model_name="productmodel",
            name="stock",
            field=models.BooleanField(default=False),
        ),
    ]
